import type { WorldState } from './types.js';

export function createInitialWorldState(): WorldState {
  return {
    clock: { day: 1, hour: 7, minute: 0 },
    started_at: new Date().toISOString(),
    environment: {
      weather: 'sunny',
      outdoor_temperature: 24,
      outdoor_noise_level: 'quiet',
    },
    rooms: {
      living_room: {
        id: 'living_room',
        name: '客廳',
        description: '一個舒適的客廳，有沙發和電視。陽光透過窗戶灑進來。',
        connections: ['kitchen', 'bedroom', 'balcony'],
        properties: { light: 'bright', temperature: 22, noise: 'quiet', outdoor: false },
        static_objects: ['sofa', 'tv'],
        current_entities: [],
        current_portable_objects: ['book_01'],
      },
      kitchen: {
        id: 'kitchen',
        name: '廚房',
        description: '一個整潔的廚房，冰箱和桌子擺放整齊。',
        connections: ['living_room'],
        properties: { light: 'bright', temperature: 22, noise: 'quiet', outdoor: false },
        static_objects: ['fridge', 'table'],
        current_entities: [],
        current_portable_objects: ['apple_01', 'apple_02', 'apple_03'],
      },
      bedroom: {
        id: 'bedroom',
        name: '臥室',
        description: '一個安靜的臥室，床鋪整潔，窗簾遮住了大部分陽光。',
        connections: ['living_room'],
        properties: { light: 'dim', temperature: 21, noise: 'quiet', outdoor: false },
        static_objects: ['bed'],
        current_entities: [],
        current_portable_objects: [],
      },
      balcony: {
        id: 'balcony',
        name: '陽台',
        description: '一個小陽台，可以看見外面的街道和天空。',
        connections: ['living_room'],
        properties: { light: 'bright', temperature: 24, noise: 'normal', outdoor: true },
        static_objects: [],
        current_entities: [],
        current_portable_objects: [],
      },
    },
    static_objects: {
      sofa: {
        id: 'sofa',
        name: '沙發',
        description: '一張舒適的三人沙發。',
        location: 'living_room',
        affordances: ['sit', 'lie'],
      },
      tv: {
        id: 'tv',
        name: '電視',
        description: '一台掛牆的大螢幕電視。',
        location: 'living_room',
        affordances: ['watch'],
      },
      fridge: {
        id: 'fridge',
        name: '冰箱',
        description: '一台白色冰箱，裡面有一些食材。',
        location: 'kitchen',
        affordances: ['open', 'look_inside'],
      },
      table: {
        id: 'table',
        name: '桌子',
        description: '一張木製餐桌，可以在這裡用餐。',
        location: 'kitchen',
        affordances: ['sit_at', 'eat_at'],
      },
      bed: {
        id: 'bed',
        name: '床',
        description: '一張舒適的雙人床，被子疊放整齊。',
        location: 'bedroom',
        affordances: ['sleep', 'lie', 'sit'],
      },
    },
    portable_objects: {
      apple_01: {
        id: 'apple_01',
        name: '蘋果',
        description: '一顆新鮮的紅蘋果。',
        location: 'kitchen',
        affordances: ['eat', 'give', 'drop'],
        consumable: true,
      },
      apple_02: {
        id: 'apple_02',
        name: '蘋果',
        description: '一顆新鮮的紅蘋果。',
        location: 'kitchen',
        affordances: ['eat', 'give', 'drop'],
        consumable: true,
      },
      apple_03: {
        id: 'apple_03',
        name: '蘋果',
        description: '一顆新鮮的紅蘋果。',
        location: 'kitchen',
        affordances: ['eat', 'give', 'drop'],
        consumable: true,
      },
      book_01: {
        id: 'book_01',
        name: '書',
        description: '一本厚厚的小說，書籤夾在中間。',
        location: 'living_room',
        affordances: ['read', 'give', 'drop'],
        consumable: false,
      },
    },
    entities: {},
  };
}
